### ISSUE TITLE
[26.1.x] NoClassDefFoundError: Could not initialize class rd.dru.SuperHravest.XMaterial

### ISSUE THREAD

**Issue by rDruTNT** [CryptoMorin/XSeries#409]
## Description

XMaterial#get is not working on 26.1.x, working fine in 1.21.x

## Code

```java
XMaterial.BOOKSHELF.get();
```

## Error

<details>
  <summary>Error stacktrace</summary>

  ```hs
[18:02:57] [Server thread/INFO]: Dru_TNT issued server command: /sh
[18:02:57] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sh' in plugin SuperHarvest v2.14.1-premium
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:935)
        at org.bukkit.craftbukkit.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:29)
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:8)
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:106)
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:480)
        at net.minecraft.commands.Commands.performCommand(Commands.java:403)
        at net.minecraft.commands.Commands.performCommand(Commands.java:390)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2190)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$0(ServerGamePacketListenerImpl.java:2166)
        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:173)
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348)
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:231)
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:147)
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1331)
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1324)
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:156)
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1155)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:358)
        at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class rd.dru.SuperHravest.XMaterial
        at rd.dru.permium.gui.PlayerUI.openPlayerUI(PlayerUI.java:37)
        at rd.dru.permium.PermiumFeature.openPlayerUI(PermiumFeature.java:659)
        at rd.dru.Commands.onCommand(Commands.java:31)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        ... 27 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at rd.dru.SuperHravest.XMaterial.<init>(XMaterial.java:1814)
        at rd.dru.SuperHravest.XMaterial.<init>(XMaterial.java:1824)
        at rd.dru.SuperHravest.XMaterial.<clinit>(XMaterial.java:68)
        at rd.dru.permium.gui.PlayerUI.openPlayerUI(PlayerUI.java:37)
        at rd.dru.permium.PermiumFeature.openPlayerUI(PermiumFeature.java:659)
        at rd.dru.Commands.onCommand(Commands.java:31)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:935)
        at org.bukkit.craftbukkit.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:29)
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:8)
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:106)
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:480)
        at net.minecraft.commands.Commands.performCommand(Commands.java:403)
        at net.minecraft.commands.Commands.performCommand(Commands.java:390)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2190)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$0(ServerGamePacketListenerImpl.java:2166)
        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:173)
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348)
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:231)
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:147)
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1331)
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1324)
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:127)
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287)
        ... 3 more
  ```

</details>

* Do not use pasting websites such as [Pastebin](https://pastebin.com/).
* Try not to include any logs (that are not stacktraces) which are unrelated to the library.

## Version
Spigot version 4626 (MC:26.1.2-R0.1)
* **XSeries:** 13.7.

**Comment by CryptoMorin** [comment]
Your stacktrace lines don't match, I don't know how you included the class in your plugin.
Also, when the error is shown like this, it usually means that the main error happened before and is not shown anymore in successive errors. Search for the first ever error that occurred with XMaterial.

**Comment by rDruTNT** [comment]
This is the full log, and the error is on the bottom, thx for help.
```java
Unbundling libraries to E:\空服拉\bundler
Starting server
Loading libraries, please wait...
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by com.sun.jna.Native in an unnamed module (file:/E:/空服拉/bundler/libraries/jna-5.17.0.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
WARNING: sun.misc.Unsafe::objectFieldOffset has been called by org.joml.MemUtil$MemUtilUnsafe (file:/E:/空服拉/bundler/libraries/joml-1.10.8.jar)
WARNING: Please consider reporting this to the maintainers of class org.joml.MemUtil$MemUtilUnsafe
WARNING: sun.misc.Unsafe::objectFieldOffset will be removed in a future release
[21:17:48] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, profilesHost=https://api.mojang.com, name=PROD]
[21:17:49] [ServerMain/INFO]: Loaded 1515 recipes
[21:17:48] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, profilesHost=https://api.mojang.com, name=PROD]
[21:17:49] [ServerMain/INFO]: Loaded 1515 recipes
[21:17:50] [Server thread/INFO]: Starting minecraft server version 26.1.2
[21:17:50] [Server thread/INFO]: Loading properties
[21:17:50] [Server thread/INFO]: This server is running Spigot version 4626-Spigot-566f972-b5ccd9c (MC: 26.1.2) (Implementing API version 26.1.2-R0.1-SNAPSHOT)
[21:17:50] [Server thread/INFO]: *** This version of Spigot contains changes to some enums. If you notice that plugins no longer work after updating, please report this to the developers of those plugins first. ***
[21:17:50] [Server thread/INFO]: *** If you cannot update those plugins, you can try setting `settings.compatibility.enum-compatibility-mode` to `true` in `bukkit.yml`. ***
[21:17:50] [Server thread/INFO]: Debug logging is disabled
[21:17:50] [Server thread/INFO]: Server Ping Player Sample Count: 12
[21:17:50] [Server thread/INFO]: Using 4 threads for Netty based IO
[21:17:50] [Server thread/INFO]: Default game type: SURVIVAL
[21:17:50] [Server thread/INFO]: Generating keypair
[21:17:50] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:17:50] [Server thread/INFO]: [SuperHarvest] Loading SuperHarvest v2.14.1-premium
[21:17:50] [Server thread/INFO]: Preparing level "world"
[21:17:50] [Server thread/ERROR]: Could not set generator for default world 'world': Plugin 'DruAdventure' does not exist
[21:17:50] [Server thread/INFO]: -------- World Settings For [world] --------
[21:17:51] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Carrot Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Potato Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Kelp Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[21:17:51] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[21:17:51] [Server thread/INFO]: Max TNT Explosions: 100
[21:17:51] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:17:51] [Server thread/INFO]: Mob Spawn Range: 4
[21:17:51] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[21:17:51] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:17:51] [Server thread/INFO]: Item Despawn Rate: 6000
[21:17:51] [Server thread/INFO]: Item Merge Radius: 2.5
[21:17:51] [Server thread/INFO]: Simulation Distance: 10
[21:17:51] [Server thread/INFO]: View Distance: 10
[21:17:51] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:17:51] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[21:17:51] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:17:51] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:17:51] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[21:17:51] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[21:17:51] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Carrot Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Potato Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Kelp Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[21:17:51] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[21:17:51] [Server thread/INFO]: Max TNT Explosions: 100
[21:17:51] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:17:51] [Server thread/INFO]: Mob Spawn Range: 4
[21:17:51] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[21:17:51] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:17:51] [Server thread/INFO]: Item Despawn Rate: 6000
[21:17:51] [Server thread/INFO]: Item Merge Radius: 2.5
[21:17:51] [Server thread/INFO]: Simulation Distance: 10
[21:17:51] [Server thread/INFO]: View Distance: 10
[21:17:51] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:17:51] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[21:17:51] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:17:51] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:17:51] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[21:17:51] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[21:17:51] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Carrot Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Potato Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Kelp Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[21:17:51] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[21:17:51] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[21:17:51] [Server thread/INFO]: Max TNT Explosions: 100
[21:17:51] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:17:51] [Server thread/INFO]: Mob Spawn Range: 4
[21:17:51] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[21:17:51] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:17:51] [Server thread/INFO]: Item Despawn Rate: 6000
[21:17:51] [Server thread/INFO]: Item Merge Radius: 2.5
[21:17:51] [Server thread/INFO]: Simulation Distance: 10
[21:17:51] [Server thread/INFO]: View Distance: 10
[21:17:51] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:17:51] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[21:17:51] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:17:51] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:17:51] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[21:17:51] [Server thread/INFO]: Loading 0 persistent chunks...
[21:17:51] [Server thread/INFO]: Preparing spawn area: 100%
[21:17:51] [Server thread/INFO]: Time elapsed: 18 ms
[21:17:51] [Server thread/INFO]: [SuperHarvest] Enabling SuperHarvest v2.14.1-premium
[21:17:51] [Server thread/ERROR]: PlaceholderAPI hook failed, please install PlaceholderAPI for it.
[21:17:52] [Server thread/INFO]: SuperHarvest Permium is enabled thx for your purchase.
[21:17:52] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:17:52] [Server thread/INFO]: Done (1.072s)! For help, type "help"
[21:17:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[21:17:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[21:17:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[21:17:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21:17:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:17:52] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:17:52] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[21:17:55] [User Authenticator #1/INFO]: UUID of player Dru_TNT is 11a256e1-1673-4e5e-acad-0548338a1c48
[21:17:55] [Server thread/ERROR]: Tried to load unrecognized recipe: ResourceKey[minecraft:recipe / modernshowcase:white_stained_glass_showcase] removed now.
[21:17:55] [Server thread/ERROR]: Tried to load unrecognized recipe: ResourceKey[minecraft:recipe / modernshowcase:light_gray_stained_glass_showcase] removed now.
[21:17:55] [Server thread/ERROR]: Tried to load unrecognized recipe: ResourceKey[minecraft:recipe / modernshowcase:glass_showcase] removed now.
[21:17:55] [Server thread/ERROR]: Tried to load unrecognized recipe: ResourceKey[minecraft:recipe / modernshowcase:white_stained_glass_showcase] removed now.
[21:17:55] [Server thread/ERROR]: Tried to load unrecognized recipe: ResourceKey[minecraft:recipe / modernshowcase:light_gray_stained_glass_showcase] removed now.
[21:17:55] [Server thread/ERROR]: Tried to load unrecognized recipe: ResourceKey[minecraft:recipe / modernshowcase:glass_showcase] removed now.
[21:17:56] [Server thread/INFO]: Dru_TNT joined the game
[21:17:56] [Server thread/INFO]: Dru_TNT[/127.0.0.1:9163] logged in with entity id 1 at ([world]-3229.800169382211, 93.0, -4371.787477997102)
[21:18:11] [Server thread/INFO]: Dru_TNT issued server command: /sh
[21:18:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sh' in plugin SuperHarvest v2.14.1-premium
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:935)
        at org.bukkit.craftbukkit.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:29)
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:8)
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:106)
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:480)
        at net.minecraft.commands.Commands.performCommand(Commands.java:403)
        at net.minecraft.commands.Commands.performCommand(Commands.java:390)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2190)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$0(ServerGamePacketListenerImpl.java:2166)
        at net.minecraft.server.TickTask.run(TickTask.java:18)
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:173)
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348)
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:231)
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:147)
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1331)
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1324)
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:127)
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1155)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:358)
        at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.ExceptionInInitializerError
        at rd.dru.SuperHravest.XMaterial.<init>(XMaterial.java:1814)
        at rd.dru.SuperHravest.XMaterial.<init>(XMaterial.java:1824)
        at rd.dru.SuperHravest.XMaterial.<clinit>(XMaterial.java:68)
        at rd.dru.permium.gui.PlayerUI.openPlayerUI(PlayerUI.java:37)
        at rd.dru.permium.PermiumFeature.openPlayerUI(PermiumFeature.java:659)
        at rd.dru.Commands.onCommand(Commands.java:31)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        ... 27 more
Caused by: java.lang.IllegalArgumentException: Failed to parse server version from: 4626-Spigot-566f972-b5ccd9c (MC: 26.1.2)
        at rd.dru.SuperHravest.XMaterial$Data.<clinit>(XMaterial.java:2372)
        ... 34 more
>
```

**Comment by CryptoMorin** [comment]
You're not using XSeries v13.7.0 as evidenced by the stacktrace lines. I tested in MC 26 and it works fine

`at rd.dru.SuperHravest.XMaterial$Data.<clinit>(XMaterial.java:2372)`

https://github.com/CryptoMorin/XSeries/blob/6da269dc0b7abd3e65026137cfed931b9a8d7515/core/src/main/java/com/cryptomorin/xseries/XMaterial.java#L2372

**Comment by rDruTNT** [comment]
You are right! after a lot of debugs, it works fine now! thx for your work
