### ISSUE TITLE
[XParticle] - NoClassDefFoundError: org/bukkit/Particle 1.8

### ISSUE THREAD

**Issue by GabrielBlink32** [CryptoMorin/XSeries#100]
**Description**
The 1.8 server does not have the org.bukkit.Particle class and is required to use packets for send particles in 1.8

My code: [https://pastebin.com/vYiZ3QqV](https://pastebin.com/vYiZ3QqV)
Issue: [https://pastebin.com/ig9BKx7T](https://pastebin.com/ig9BKx7T)
**Version**
Spigot 1.8 and XSeries version 7.8.0

**Comment by CryptoMorin** [comment]
Yes, XParticle is not intended to work with 1.8
If you want to support 1.8 you can start from [this example](https://github.com/CryptoMorin/XSeries/wiki#18-full-particle-support-based-on-particledisplay).
